config/routes.rb
Rails.application.routes.draw do
  root 'farmlog#index'

  devise_for :users
  
  resources :events do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
  mount_uploader :picture, PictureUploader


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event
  before_action :set_comment, only: :destroy

  def create
    @comment = @event.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

  end

  def destroy
    @comment.destroy
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :image, :picture, :picture_cache)
    end
end

app/controllers/farmlog_controller.rb
class FarmlogController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/farmlog_helper.rb
module FarmlogHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%=comment.id %>">
  <%= comment.content %>,
  <%= time_ago_in_words(comment.created_at) %> ago
  <%= comment.user.name %>
  <%= link_to "x", [comment.event, comment], method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
</li>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comment_header">
    <h2>Comments:</h2>
  </div>
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>
  <div class='comments_form'>
    <%= render "comments/form" %>
  </div>
</div>

app/views/comments/_form.html.erb
<% comment = @event.comments.new %>
<div id="comments_form_<%=@event.id%>">
<%= simple_form_for([@event, comment], remote: true ) do | f | %>
  <div class='form-inputs'>
    <%= f.input :content, label: false, placeholder: 'Add a comment.',  input_html: { rows: 5 } %>
  </div>
  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@event.id%>">
<% if @event.comments.size > 0 %>
  <%= render @event.comments %>
<% else %>
  <li>
    No comments
  </li>
<% end %>
</ul>

app/views/comments/create.js.erb
<% if @comment.errors.size == 0 %>
  $('<%=j render @comment %>').appendTo($("#comments_list_<%=@event.id %>")).hide().fadeIn('fast');
  $("#comments_form_<%=@event.id %> form")[0].reset();
<% else %>
  alert("Please submit after commenting...");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, input_html: { rows: 10 } %>
    <%= f.input :picture, as: :file %>
    <%= f.hidden_field :picture_cache %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h2>Update</h2>

<%= render 'form' %>

<hr>

<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/index.html.erb
<h2>저 아름다운 땀방울을 보라</h2>

<br>

<%= link_to "사진 추가", new_event_path, class: "btn btn-default" %>

<br>
<br>

<table class="table">
  <thead>
    <tr>
      <th>우리들의 이야기</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to image_tag(event.picture), event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h2>New farmlog</h2>

<%= render 'form' %>

<hr>

<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/show.html.erb
<h2>
	<strong><%= @event.title %></strong>: <%= @event.content %>
</h2>

<div class="row">
	<div class="col-sm-6">
		<p>
			<%= image_tag(@event.picture) %>
		</p>
		<p>
			<strong><%= @event.user.name %></strong>
		</p>
		<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-default' %>
		<%= link_to 'Destroy', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
		<%= link_to 'Back', events_path, class: 'btn btn-default' %>
	</div>

	<div class="col-sm-6">
		<%= render "comments/comments" %>
	</div>
<hr>
</div>

app/views/farmlog/index.html.erb
<%= link_to "Farmcamping에 당신을 초대합니다", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Farmlog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        	<li><%= link_to "Log out", destroy_user_session_path, class: "navbar-right", method: :delete %></li>
        <% else %>
        	<li><%= link_to "Log in", new_user_session_path, class: "navbar-right" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
 	<%= yield %>
</div>

</body>
</html>